### ISSUE TITLE
Repeatable Bug: Crash during full inventory crafting + Found possible culprit code

### ISSUE THREAD

**Issue by UberWaffe** [LepkoQQ/EasyCrafting#5] opened 2012-11-12 19:24 UTC
I've found a repeatable bug with the easycraft table, in that whenever you you have a full inventory (just one open slot left) and craft something (right-click max craft) the game will crash with the following error report (just the last few lines).
The crash occurs regardless if recursion is needed in the craft or not (somewhat strange, see possible culprit below)

2012-11-12 19:24:01 [INFO] [STDERR] java.lang.NullPointerException
2012-11-12 19:24:01 [INFO] [STDERR]     at qf.a(SourceFile:225)
2012-11-12 19:24:01 [INFO] [STDERR]     at net.lepko.minecraft.easycrafting.Recipes.checkIngredients(Recipes.java:123)
2012-11-12 19:24:01 [INFO] [STDERR]     at net.lepko.minecraft.easycrafting.Recipes.hasIngredients(Recipes.java:71)
2012-11-12 19:24:01 [INFO] [STDERR]     at net.lepko.minecraft.easycrafting.Recipes.getCraftableRecipes(Recipes.java:61)
2012-11-12 19:24:01 [INFO] [STDERR]     at net.lepko.minecraft.easycrafting.GuiEasyCrafting.refreshCraftingOutput(GuiEasyCrafting.java:288)
2012-11-12 19:24:01 [INFO] [STDERR]     at net.lepko.minecraft.easycrafting.TickHandlerClient.tickEnd(TickHandlerClient.java:34)
2012-11-12 19:24:01 [INFO] [STDERR]     at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
2012-11-12 19:24:01 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:135)
2012-11-12 19:24:01 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:359)
2012-11-12 19:24:01 [INFO] [STDERR]     at net.minecraft.client.Minecraft.l(Minecraft.java:1849)
2012-11-12 19:24:01 [INFO] [STDERR]     at net.minecraft.client.Minecraft.J(Minecraft.java:854)
2012-11-12 19:24:01 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:779)
2012-11-12 19:24:01 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2012-11-12 19:24:11 [INFO] [STDOUT] Stopping!

Note the problem lies in Recipes.checkIngredients

I've found the culprit code to be this line:
if (takeIngredients(ingRecipe.ingredients, tmp, recursionCount + 1) && tmp.addItemStackToInventory(ingRecipe.result.copy())) {

I suspect that if no valid open slot is available for the minecraft addItemStackToInventory() function to drop the items into, then it goes insane.

I tested setting the recursionCount = 1 in the config, and the bug vanished (so the problem lies somewhere in those 7 lines of code, so must be that line.), along with the ability to recursively craft.

The strange part is that the code seemed to execute even when recursion shouldn't be needed, but I am perhaps just mistaken on this last point.
[Update] Definitely crashes even when recursion is not needed. Did cobblestone to cobblestone slabs easycraft, game crashed when recursionCount > 1. Does not crash if recursionCount = 1.

[Update] Oh, yes. If you get the crash. Then next time you try and open the crafting table it immediately crashes again upon trying to open the GUI.
A workaround is to break and place the table back down again. But crash will occur if 'full-inventory' scenario is repeated.

**Comment by LepkoQQ** [comment] 2012-11-12 19:45
I think the issue is that I try to put tmp.addItemStackToInventory() and the inventory tmp doesnt have a player assigned (tmp.player = null)

The method in the crash log qf.a() tries to get player capabilities from that inventory and that results in a NPE.

Fixed in my build. Didnt push the update yet. Will do later.

**Closed as completed by LepkoQQ** 2012-11-12 19:45 UTC
