### ISSUE TITLE
Crash with MCPC+ on load

### ISSUE THREAD

**Issue by adamish717** [LepkoQQ/EasyCrafting#16] opened 2013-01-30 07:22 UTC
I believe it has to do with Null recipes as mentioned in Issue #13.  I understand MCPC+ isn't standard Forge server, but it's probably worth looking in to.

No other mods loaded.

// Sorry :(

Time: 1/29/13 10:46 PM
Description: Exception in server tick loop

java.lang.NullPointerException
    at net.lepko.easycrafting.easyobjects.EasyItemStack.fromItemStack(EasyItemStack.java:71)
    at net.lepko.easycrafting.helpers.RecipeHelper.scanRecipes(RecipeHelper.java:71)
    at net.lepko.easycrafting.handlers.EventHandler.onWorldLoad(EventHandler.java:15)
    at net.minecraftforge.event.ASMEventHandler_37_EventHandler_onWorldLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraft.server.MinecraftServer.initOverWorld(MinecraftServer.java:454)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:339)
    at ho.c(DedicatedServer.java:195)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:660)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LepkoQQ** [comment] 2013-01-30 11:20
It seems its not compatible with MCPC+. I will look in to it for next version. Thanks for the report.

**Comment by adamish717** [comment] 2013-01-30 17:52
I would recommend working with Blood or Agaricus @ #MCPortCentral as they're also interested in solving the problem.  
The issue is @ https://github.com/MinecraftPortCentral/MCPC-Plus/issues/139

**Comment by agaricusb** [comment] 2013-01-31 05:53
Hi @LepkoQQ – I looked into this problem for MCPC+, turns out the problem is with RecipesArmorDyes and RecipesMapCloning returning null for getRecipeOutput().

On a vanilla server, these recipes are skipped as unknown classes. However, CraftBukkit changed them to inherit from ShapelessRecipe, so they match 'r instanceof ShapedRecipes' on https://github.com/LepkoQQ/EasyCrafting/blob/master/src/net/lepko/easycrafting/helpers/RecipeHelper.java#L59 , which then causes the null dereference in the EasyItemStack constructor.

Not sure of the best fix here.. was considering removing the 'extends ShapelessRecipe' addition by CraftBukkit, in MCPC+ but this would could Bukkit plugins.. alternatively if you're interested, a fix could be implemented in EasyCrafting instead. Could either check if the recipe is RecipesArmorDyes/RecipesMapCloning before ShapedRecipes, or treat recipes with null output as 'unknown'. Submitted a PR with the latter change here: https://github.com/LepkoQQ/EasyCrafting/pull/17 - with this change, EasyCrafting loads without error on MCPC+ build 78 (and appears to be fully functional, though I'm not familiar enough with the mod to say for sure). Hope this helps.

**Comment by LepkoQQ** [comment] 2013-03-22 17:05
closed via cc64c1b, thank you for the report and solution.

**Closed as completed by LepkoQQ** 2013-03-22 17:05 UTC
